### ISSUE TITLE
Binary download fails with AuthenticationFailed

### ISSUE THREAD

**Issue by nethrose** [Elestriel/Corsair-RGB-Keyboard-Spectrograph#10]
Hellooooo 👋 

Unfortunately, your spectrograph [download location](https://perifx.file.core.windows.net/drop/cee/CEE%200.3.39.zip?sv=2019-12-12&ss=f&srt=co&sp=rl&se=2022-01-01T00:09:20Z&st=2021-01-01T16:09:20Z&spr=https,http&sig=UoAQRjPAqz2S6FSMBDcUu3Npc19UBdmYaFwVf33w8Gw%3D) kicks out this `AuthenticationFailed` error:

```
<Error>
<Code>AuthenticationFailed</Code>
<Message>
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:8c894251-f01a-002c-4b09-1e63d7000000 Time:2022-02-09T23:06:37.3633204Z
</Message>
<AuthenticationErrorDetail>
Signature not valid in the specified time frame: Start [Fri, 01 Jan 2021 16:09:20 GMT] - Expiry [Sat, 01 Jan 2022 00:09:20 GMT] - Current [Wed, 09 Feb 2022 23:06:37 GMT]
</AuthenticationErrorDetail>
</Error>
```

I used this little app a ton, not long ago, and lost it after a Windows reinstall. Would love to get it back =D

Maybe just a GitHub release instead of hosting it on your site?

**Comment by Elestriel** [comment]
Thanks for making the article! I simply forgot to update the key for the storage account where it's stored. Like a big chungus.

Should be working now!

**Comment by nethrose** [comment]
That was fast; tysm!!
